# Build stage
FROM golang:1.19-alpine3.16 AS builder
WORKDIR /packages
COPY /packages .
COPY ./integration-test/go.mod ./integration-test/go.sum /modules/
WORKDIR /modules
RUN go mod download

# Run stage
FROM golang:1.19-alpine3.16
COPY --from=builder /packages /packages
COPY --from=builder /go/pkg /go/pkg
COPY ./integration-test /app
WORKDIR /app

RUN go env -w CGO_ENABLED=0
RUN go env -w GOOS=linux
RUN go env -w GOARCH=amd64

CMD ["go", "test", "-v", "./..."]